// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Клуб_6.Models;

#nullable disable

namespace Клуб_6.Migrations
{
    [DbContext(typeof(КлубContext))]
    [Migration("20260324055343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Клуб_6.Models.Criterion", b =>
                {
                    b.Property<int>("CriterionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CriterionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterionID"));

                    b.Property<int?>("CompositionID")
                        .HasColumnType("int")
                        .HasColumnName("CompositionID");

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsImportant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("CriterionID")
                        .HasName("PK__Criteria__647C3BD1AA41C4FB");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("Клуб_6.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DisciplineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<int?>("Coefficient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("CompositionID")
                        .HasColumnType("int")
                        .HasColumnName("CompositionID");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("WorkingScore")
                        .HasColumnType("int");

                    b.HasKey("DisciplineId")
                        .HasName("PK__Discipli__29093750E59CB0B5");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Клуб_6.Models.Dog", b =>
                {
                    b.Property<int>("ChipNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int")
                        .HasColumnName("HeightCM");

                    b.Property<bool?>("IsAlive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("KennelId")
                        .HasColumnType("int")
                        .HasColumnName("KennelID");

                    b.Property<string>("MotherName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("WeightKg")
                        .HasColumnType("int")
                        .HasColumnName("WeightKG");

                    b.HasKey("ChipNumber")
                        .HasName("PK__Dogs__7460557C7A3AB5C3");

                    b.HasIndex("KennelId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("Клуб_6.Models.DogCriteriaResults_DogList", b =>
                {
                    b.Property<int>("ResultIdRecordIdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResultID_RecordID_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultIdRecordIdId"));

                    b.Property<int>("CriterionId")
                        .HasColumnType("int")
                        .HasColumnName("CriterionID");

                    b.Property<int>("OptionId")
                        .HasColumnType("int")
                        .HasColumnName("OptionID");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    b.Property<string>("UserInput")
                        .HasColumnType("text");

                    b.HasKey("ResultIdRecordIdId")
                        .HasName("PK__DogCrite__AA41C4FB12345678");

                    b.HasIndex("CriterionId");

                    b.HasIndex(new[] { "RecordId" }, "IX_DogCriteriaResults_DogList_RecordID");

                    b.ToTable("DogCriteriaResults_DogList", (string)null);
                });

            modelBuilder.Entity("Клуб_6.Models.DogDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("DisciplineID");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DogDisci__3214EC27DC7E3462");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("RecordId");

                    b.ToTable("DogDisciplines");
                });

            modelBuilder.Entity("Клуб_6.Models.DogList", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("DogId")
                        .HasColumnType("int")
                        .HasColumnName("DogID");

                    b.Property<string>("DogName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    b.Property<string>("Owner")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TrialFailed")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("TrialFailed");

                    b.Property<int?>("TrialPassed")
                        .HasColumnType("int")
                        .HasColumnName("TrialPassed");

                    b.HasKey("RecordId")
                        .HasName("PK__DogList__FBDF78C92E05AB2D");

                    b.HasIndex("DogId");

                    b.HasIndex("EventId");

                    b.ToTable("DogList", (string)null);
                });

            modelBuilder.Entity("Клуб_6.Models.DogOwner", b =>
                {
                    b.Property<int>("DogOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DogOwnerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DogOwnerId"));

                    b.Property<int>("ChipNumber")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.HasKey("DogOwnerId")
                        .HasName("PK__DogOwner__EA0FED7342E7CAF5");

                    b.HasIndex("ChipNumber");

                    b.HasIndex("OwnerId");

                    b.ToTable("DogOwners");
                });

            modelBuilder.Entity("Клуб_6.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("CommitteeChairman")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CompositionId")
                        .HasColumnType("int")
                        .HasColumnName("CompositionID");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventVenue")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Host")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Judge1")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Judge2")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Organization")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TestOrganizer")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EventId")
                        .HasName("PK__Events__7944C8708520FBCD");

                    b.HasIndex("CompositionId");

                    b.HasIndex("StatusId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Клуб_6.Models.EventComposition", b =>
                {
                    b.Property<int>("CompositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompositionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompositionId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CompositionId")
                        .HasName("PK__EventCom__B8E2333F11031CD1");

                    b.ToTable("EventComposition", (string)null);
                });

            modelBuilder.Entity("Клуб_6.Models.EventStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__EventSta__C8EE2063DB185660");

                    b.ToTable("EventStatuses");
                });

            modelBuilder.Entity("Клуб_6.Models.Kennel", b =>
                {
                    b.Property<int>("KennelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KennelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KennelId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Kazakhstan");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("KennelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("KennelId")
                        .HasName("PK__Kennels__921B7EC337B69530");

                    b.ToTable("Kennels");
                });

            modelBuilder.Entity("Клуб_6.Models.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<int?>("CompositionID")
                        .HasColumnType("int")
                        .HasColumnName("CompositionID");

                    b.Property<int?>("CriterionID")
                        .HasColumnType("int")
                        .HasColumnName("CriterionID");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OptionValue")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TextInfo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("OptionId")
                        .HasName("PK__Options__92C7A1DF0928F6DE");

                    b.HasIndex("CriterionID");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Клуб_6.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("OwnerId")
                        .HasName("PK__Owners__8193859888119E94");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Клуб_6.Models.Dog", b =>
                {
                    b.HasOne("Клуб_6.Models.Kennel", "Kennel")
                        .WithMany("Dogs")
                        .HasForeignKey("KennelId")
                        .HasConstraintName("FK__Dogs__KennelID__4F7CD00D");

                    b.Navigation("Kennel");
                });

            modelBuilder.Entity("Клуб_6.Models.DogCriteriaResults_DogList", b =>
                {
                    b.HasOne("Клуб_6.Models.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .IsRequired()
                        .HasConstraintName("FK__DogCritResDogList__Criterion");

                    b.HasOne("Клуб_6.Models.DogList", "Record")
                        .WithMany("DogCriteriaResultsDogLists")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("FK__DogList__DogCritResDogList");

                    b.Navigation("Criterion");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Клуб_6.Models.DogDiscipline", b =>
                {
                    b.HasOne("Клуб_6.Models.Discipline", "Discipline")
                        .WithMany("DogDisciplines")
                        .HasForeignKey("DisciplineId")
                        .IsRequired()
                        .HasConstraintName("FK__DogDiscip__Disci__7C4F7684");

                    b.HasOne("Клуб_6.Models.DogList", "Record")
                        .WithMany("DogDisciplines")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("FK__DogDiscip__Recor__7B5B524B");

                    b.Navigation("Discipline");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Клуб_6.Models.DogList", b =>
                {
                    b.HasOne("Клуб_6.Models.Dog", "Dog")
                        .WithMany("DogLists")
                        .HasForeignKey("DogId")
                        .IsRequired()
                        .HasConstraintName("FK__DogList__DogID__6FE99F9F");

                    b.HasOne("Клуб_6.Models.Event", "Event")
                        .WithMany("DogLists")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__DogList__EventID__6EF57B66");

                    b.Navigation("Dog");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Клуб_6.Models.DogOwner", b =>
                {
                    b.HasOne("Клуб_6.Models.Dog", "ChipNumberNavigation")
                        .WithMany("DogOwners")
                        .HasForeignKey("ChipNumber")
                        .IsRequired()
                        .HasConstraintName("FK__DogOwners__ChipN__5629CD9C");

                    b.HasOne("Клуб_6.Models.Owner", "Owner")
                        .WithMany("DogOwners")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__DogOwners__Owner__5535A963");

                    b.Navigation("ChipNumberNavigation");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Клуб_6.Models.Event", b =>
                {
                    b.HasOne("Клуб_6.Models.EventComposition", "Composition")
                        .WithMany("Events")
                        .HasForeignKey("CompositionId")
                        .HasConstraintName("FK__Events__Composit__6E01572D");

                    b.HasOne("Клуб_6.Models.EventStatus", "Status")
                        .WithMany("Events")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Events__StatusId__6D0D32F4");

                    b.Navigation("Composition");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Клуб_6.Models.Option", b =>
                {
                    b.HasOne("Клуб_6.Models.Criterion", "Criterion")
                        .WithMany("Options")
                        .HasForeignKey("CriterionID")
                        .HasConstraintName("FK_Options_Criteria");

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("Клуб_6.Models.Criterion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Клуб_6.Models.Discipline", b =>
                {
                    b.Navigation("DogDisciplines");
                });

            modelBuilder.Entity("Клуб_6.Models.Dog", b =>
                {
                    b.Navigation("DogLists");

                    b.Navigation("DogOwners");
                });

            modelBuilder.Entity("Клуб_6.Models.DogList", b =>
                {
                    b.Navigation("DogCriteriaResultsDogLists");

                    b.Navigation("DogDisciplines");
                });

            modelBuilder.Entity("Клуб_6.Models.Event", b =>
                {
                    b.Navigation("DogLists");
                });

            modelBuilder.Entity("Клуб_6.Models.EventComposition", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Клуб_6.Models.EventStatus", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Клуб_6.Models.Kennel", b =>
                {
                    b.Navigation("Dogs");
                });

            modelBuilder.Entity("Клуб_6.Models.Owner", b =>
                {
                    b.Navigation("DogOwners");
                });
#pragma warning restore 612, 618
        }
    }
}
